# Generated by Django 4.2.24 on 2025-09-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllContacts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lead_id", models.IntegerField(blank=True, null=True)),
                (
                    "rut",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ruteje",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "glosa",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("feccomp", models.DateField(blank=True, null=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "respuesta",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "All_contacts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_cheque",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        db_column="N_cheque",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fecha_ven_cheque",
                    models.DateField(
                        blank=True, db_column="Fecha_ven_cheque", null=True
                    ),
                ),
                (
                    "importe_pago",
                    models.DecimalField(
                        blank=True,
                        db_column="Importe_pago",
                        decimal_places=0,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "doc_pago",
                    models.DecimalField(
                        blank=True,
                        db_column="Doc_Pago",
                        decimal_places=0,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "rut_cli",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        db_column="Rut_Cli",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "socio_comercial",
                    models.IntegerField(
                        blank=True, db_column="Socio_comercial", null=True
                    ),
                ),
                (
                    "fecha_contabiliza",
                    models.DateField(
                        blank=True, db_column="Fecha_Contabiliza", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Cheque",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Descuento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ic", models.IntegerField(blank=True, null=True)),
                ("cc", models.IntegerField(blank=True, null=True)),
                (
                    "deuda_total",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "descuento_total",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tipo_descuento",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tp_dcto",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        db_column="Tp_Dcto",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nombre_camp",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        db_column="Nombre_Camp",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dcto_extraordinario",
                    models.CharField(
                        blank=True,
                        db_collation="Modern_Spanish_CI_AS",
                        db_column="Dcto_Extraordinario",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Descuento",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Deuda",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ic", models.IntegerField(blank=True, null=True)),
                ("monto", models.IntegerField(blank=True, null=True)),
                ("contador", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Deuda",
                "managed": False,
            },
        ),
    ]
