# Generated by Django 4.2.24 on 2025-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarteraTotales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(blank=True, max_length=11, null=True)),
                ("CtaCto", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "boletas",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "other_Table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NewEmailSvia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.IntegerField(blank=True, null=True)),
                ("rut", models.CharField(blank=True, max_length=12, null=True)),
                ("ruteje", models.CharField(blank=True, max_length=12, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "db_table": "new_table",
                "managed": False,
            },
        ),
    ]
