# Generated by Django 4.2.24 on 2025-09-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_carteratotales_newemailsvia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carteratotales",
            options={},
        ),
        migrations.AlterModelOptions(
            name="newemailsvia",
            options={},
        ),
    ]
